### ISSUE TITLE
Reading biom files in R causes an X to be added to column names that start with #

### ISSUE THREAD

**Issue by nearinj** [gibsramen/qadabra#24]
Hey Gibs,

I tried running the workflow and ran into an error that I believe is being caused by the way you are reading in the biom tables in R. When the biom tables are read in R if the OTUs/ASVs have #s at the start. I.e. if the original ASV was called: 

"6d5af1db8934361889a6fb8d80c70836"

it will be changed into the R table to
"X6d5af1db8934361889a6fb8d80c70836"

This doesn't cause an issue when running the tools, however, i believe it is causing downstream issues when the original biom file is then read in by the log_ratios python script which to my knowledge doesn't add an X character to column names that start with a #.  

rule log_ratios:
    input: ../data/Chemerin_ASVs_table.biom, results/ml/maaslin2/pctile_feats/pctile_20.tsv
    output: results/ml/maaslin2/log_ratios/log_ratios.pctile_20.tsv
    log: log/log_ratios.maaslin2.pctile_20.log
    jobid: 139
    reason: Missing output files: results/ml/maaslin2/log_ratios/log_ratios.pctile_20.tsv
    wildcards: tool=maaslin2, pctile=20
    resources: tmpdir=/tmp

It would be easiest to fix this if you can turn off the checkname option in the table read of the R scripts.  However looking at the read_biom function it doesn't seem to be an option.

**Comment by gibsramen** [comment]
Good catch - didn't even consider that. I'll look into munging the biom/table names to address this. Thanks!
